/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param walletId The Node-specific identifier of the Wallet that is sharing the credentials for the Group
 * @param groupId The unique identifier of the Group whose credentials will be shared
 * @param readPermission Boolean that should be set to true if and only if read permission should be shared. Note that write permission is always shared and there's no option for read-only permission. Defaults to false.
 * @param memo Memo to be used by the application to define the purpose of the group and why its credentials were shared. Should include information about who is sharing the group if this information is relevant. Defaults to an empty string
 * @param recipientAddress An Address of the Wallet with which the Group credentials should be shared
 */
data class AddToGroupRequest (
    /* The Node-specific identifier of the Wallet that is sharing the credentials for the Group */
    val walletId: kotlin.String,
    /* The unique identifier of the Group whose credentials will be shared */
    val groupId: kotlin.String,
    /* An Address of the Wallet with which the Group credentials should be shared */
    val recipientAddress: kotlin.String,
    /* Boolean that should be set to true if and only if read permission should be shared. Note that write permission is always shared and there's no option for read-only permission. Defaults to false. */
    val readPermission: kotlin.Boolean? = null,
    /* Memo to be used by the application to define the purpose of the group and why its credentials were shared. Should include information about who is sharing the group if this information is relevant. Defaults to an empty string */
    val memo: kotlin.String? = null
) {

}

