/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AnalyticsConfidentialIssuanceDescription
import org.openapitools.client.models.AnalyticsOutputDescription
import org.openapitools.client.models.AnalyticsPublicIssuanceDescription

/**
 * 
 * @param isConfidential Boolean signifying whether the Issuance was done confidentially; false if the Issuance was done publicly
 * @param publicIssuanceDescription 
 * @param confidentialIssuanceDescription 
 * @param outputDescription 
 */
data class AnalyticsOutput (
    /* Boolean signifying whether the Issuance was done confidentially; false if the Issuance was done publicly */
    val isConfidential: kotlin.Boolean? = null,
    val publicIssuanceDescription: AnalyticsPublicIssuanceDescription? = null,
    val confidentialIssuanceDescription: AnalyticsConfidentialIssuanceDescription? = null,
    val outputDescription: AnalyticsOutputDescription? = null
) {

}

