/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param isIncoming Boolean signifying whether the Assets were transferred to the Wallet in question; false of the Assets were transferred from the Wallet into another
 * @param senderId The public key of the Wallet the Assets were transferred from
 * @param recipientAddress The address of the Wallet the Assets were transferred to
 * @param confirmedBy The public key of the Wallet that confirmed receipt of this transfer
 * @param assetId The ID of an Asset Type. It must be a string of length 0 to 40 characters. Allowed characters are lower- and uppercase letters, digits, dot (.), and hyphen (-). It must not end with an hyphen. Asset IDs are case-sensitive. 
 * @param amount The amount of Assets transferred
 * @param memo The private memo attached to the Transfer
 */
data class AnalyticTransferWalletTx (
    /* Boolean signifying whether the Assets were transferred to the Wallet in question; false of the Assets were transferred from the Wallet into another */
    val isIncoming: kotlin.Boolean? = null,
    /* The public key of the Wallet the Assets were transferred from */
    val senderId: kotlin.String? = null,
    /* The address of the Wallet the Assets were transferred to */
    val recipientAddress: kotlin.String? = null,
    /* The public key of the Wallet that confirmed receipt of this transfer */
    val confirmedBy: kotlin.String? = null,
    /* The ID of an Asset Type. It must be a string of length 0 to 40 characters. Allowed characters are lower- and uppercase letters, digits, dot (.), and hyphen (-). It must not end with an hyphen. Asset IDs are case-sensitive.  */
    val assetId: kotlin.String? = null,
    /* The amount of Assets transferred */
    val amount: kotlin.Int? = null,
    /* The private memo attached to the Transfer */
    val memo: kotlin.String? = null
) {

}

