/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AnalyticsTxType

/**
 * 
 * @param type 
 * @param txHash the QEDIT-generated hash of the transaction
 * @param blockHeight The height of the Block (inside the Blockchain) that the transaction is a part of
 * @param blockHash the hash of the Block (inside the Blockchain) that the transaction is a part of
 * @param timestamp UTC time of creation of the time the Block containing the transaction was created in RFC-3339 format
 * @param indexInBlock The serial number within the Block of the transaction relative to other QEDIT transactions; indexing is 0-based
 */
data class AnalyticsTxMetadata (
    val type: AnalyticsTxType? = null,
    /* the QEDIT-generated hash of the transaction */
    val txHash: kotlin.String? = null,
    /* The height of the Block (inside the Blockchain) that the transaction is a part of */
    val blockHeight: kotlin.Int? = null,
    /* the hash of the Block (inside the Blockchain) that the transaction is a part of */
    val blockHash: kotlin.String? = null,
    /* UTC time of creation of the time the Block containing the transaction was created in RFC-3339 format */
    val timestamp: kotlin.String? = null,
    /* The serial number within the Block of the transaction relative to other QEDIT transactions; indexing is 0-based */
    val indexInBlock: kotlin.Int? = null
) {

}

