/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AnalyticsRuleWalletDefinition

/**
 * 
 * @param signedBySelf Boolean signifying whether the Rule was created by the Wallet in question
 * @param ruleAffectSelf Boolean signifying whether the Rule granted permissions to the Wallet in question
 * @param txSigner The public key of the Wallet that was used to create the Rule
 * @param rule 
 */
data class AnalyticRuleWalletTx (
    /* Boolean signifying whether the Rule was created by the Wallet in question */
    val signedBySelf: kotlin.Boolean? = null,
    /* Boolean signifying whether the Rule granted permissions to the Wallet in question */
    val ruleAffectSelf: kotlin.Boolean? = null,
    /* The public key of the Wallet that was used to create the Rule */
    val txSigner: kotlin.String? = null,
    val rule: AnalyticsRuleWalletDefinition? = null
) {

}

