/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AnalyticsTxType

/**
 * 
 * @param type 
 * @param txHash The QEDIT-generated hash of the transaction
 * @param timestamp UTC time of creation of the time the Block containing the transaction was created in RFC-3339 format
 */
data class AnalyticWalletMetadata (
    val type: AnalyticsTxType? = null,
    /* The QEDIT-generated hash of the transaction */
    val txHash: kotlin.String? = null,
    /* UTC time of creation of the time the Block containing the transaction was created in RFC-3339 format */
    val timestamp: kotlin.String? = null
) {

}

