/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param errorCode The error code returned from the server
 * @param message The error message returned from the server
 */
data class ErrorResponse (
    /* The error code returned from the server */
    val errorCode: kotlin.Int,
    /* The error message returned from the server */
    val message: kotlin.String? = null
) {

}

