/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param walletId The ID of the Wallet to export a viewing key for
 * @param authorization The authorization password for the Wallet
 * @param recipientPaymentAddress The Address of the Wallet that belongs to the intended recipient of the exported viewing key; used to encrypt the key in such a way that only the intended recipient can decrypt it
 */
data class ExportAuditorAccessWalletRequest (
    /* The ID of the Wallet to export a viewing key for */
    val walletId: kotlin.String,
    /* The authorization password for the Wallet */
    val authorization: kotlin.String,
    /* The Address of the Wallet that belongs to the intended recipient of the exported viewing key; used to encrypt the key in such a way that only the intended recipient can decrypt it */
    val recipientPaymentAddress: kotlin.String
) {

}

