/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param walletId The ID under which to create the Wallet; must be unique within the Node
 * @param authorization The authorizarion password under which to encrypt the generated Wallet's secret key; will be required in order to perform actions using the Wallet
 */
data class GenerateWalletRequest (
    /* The ID under which to create the Wallet; must be unique within the Node */
    val walletId: kotlin.String,
    /* The authorizarion password under which to encrypt the generated Wallet's secret key; will be required in order to perform actions using the Wallet */
    val authorization: kotlin.String
) {

}

