/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.OrderEnum
import org.openapitools.client.models.Result
import org.openapitools.client.models.TaskType

/**
 * 
 * @param startIndex An offset used to paginate through the Task list; indexing is 0-based
 * @param numberOfResults Maximal number of results to fetch in this call
 * @param types Types of Tasks to fetch; fetch all types if omitted
 * @param results List of results (statuses) to filter by; fetch in_progress tasks if omitted
 * @param order 
 */
data class GetTasksRequest (
    /* An offset used to paginate through the Task list; indexing is 0-based */
    val startIndex: kotlin.Int,
    /* Maximal number of results to fetch in this call */
    val numberOfResults: kotlin.Int,
    /* Types of Tasks to fetch; fetch all types if omitted */
    val types: kotlin.Array<TaskType>? = null,
    /* List of results (statuses) to filter by; fetch in_progress tasks if omitted */
    val results: kotlin.Array<Result>? = null,
    val order: OrderEnum? = null
) {

}

