/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.AnalyticWalletTx

/**
 * 
 * @param walletId 
 * @param transactions The list of retrieved transactions
 */
data class GetWalletActivityResponse (
    val walletId: kotlin.String? = null,
    /* The list of retrieved transactions */
    val transactions: kotlin.Array<AnalyticWalletTx>? = null
) {

}

