/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.HealthcheckResponseItem

/**
 * 
 * @param version API version of the Node
 * @param blockchainConnector 
 * @param messageQueue 
 * @param database 
 * @param passing Boolean signifying whether the endpoint is ready for calls
 */
data class HealthcheckResponse (
    /* API version of the Node */
    val version: kotlin.String? = null,
    val blockchainConnector: HealthcheckResponseItem? = null,
    val messageQueue: HealthcheckResponseItem? = null,
    val database: HealthcheckResponseItem? = null,
    /* Boolean signifying whether the endpoint is ready for calls */
    val passing: kotlin.Boolean? = null
) {

}

