/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param walletId The ID under which to import the Wallet; can be different from the ID the Wallet was stored under in the exporting Node
 * @param encryptedKey The encrypted secret key of the Wallet
 * @param authorization The authorization password used during Wallet generation that allows to decrypt the encrypted secret key
 */
data class ImportWalletRequest (
    /* The ID under which to import the Wallet; can be different from the ID the Wallet was stored under in the exporting Node */
    val walletId: kotlin.String,
    /* The encrypted secret key of the Wallet */
    val encryptedKey: kotlin.String,
    /* The authorization password used during Wallet generation that allows to decrypt the encrypted secret key */
    val authorization: kotlin.String
) {

}

