/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param walletId The ID of the Wallet that has the required Issuance privileges
 * @param authorization The authorization password for the Wallet that has the Issuance privileges
 * @param recipientAddress The Address of the recipient of the issued Assets
 * @param assetId The ID of an Asset Type. It must be a string of length 0 to 40 characters. Allowed characters are lower- and uppercase letters, digits, dot (.), and hyphen (-). It must not end with an hyphen. Asset IDs are case-sensitive. 
 * @param amount the amount of Assets to issue
 * @param confidential Boolean which should be true if the issuance should be confidential, and false of the Issuance should be public
 * @param memo An app-customizable field to store additional private data relating to the issuance; the memo is shared between the sender and the receiver, but is not divulged to other parties
 * @param attachmentIds The globally-unique identifiers of the Attachments to attach to the issued Asset; the attachments must already be uploaded, and their identifiers are returned by the upload endpoint
 */
data class IssueAssetRequest (
    /* The ID of the Wallet that has the required Issuance privileges */
    val walletId: kotlin.String,
    /* The authorization password for the Wallet that has the Issuance privileges */
    val authorization: kotlin.String,
    /* The Address of the recipient of the issued Assets */
    val recipientAddress: kotlin.String,
    /* The ID of an Asset Type. It must be a string of length 0 to 40 characters. Allowed characters are lower- and uppercase letters, digits, dot (.), and hyphen (-). It must not end with an hyphen. Asset IDs are case-sensitive.  */
    val assetId: kotlin.String,
    /* the amount of Assets to issue */
    val amount: kotlin.Int,
    /* Boolean which should be true if the issuance should be confidential, and false of the Issuance should be public */
    val confidential: kotlin.Boolean,
    /* An app-customizable field to store additional private data relating to the issuance; the memo is shared between the sender and the receiver, but is not divulged to other parties */
    val memo: kotlin.String,
    /* The globally-unique identifiers of the Attachments to attach to the issued Asset; the attachments must already be uploaded, and their identifiers are returned by the upload endpoint */
    val attachmentIds: kotlin.Array<kotlin.String>? = null
) {

}

