/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* The type of notification. This also determines the type of the content of the notification.
* Values: completedSuccessfully,failed
*/
enum class NotificationType(val value: kotlin.String){

    @Json(name = "task_completed_successfully") completedSuccessfully("task_completed_successfully"),

    @Json(name = "task_failed") failed("task_failed");

}

