/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param walletId The ID of the Wallet to export a viewing key for
 * @param authorization The authorization password for the Wallet
 * @param recipientPaymentAddress An Address of the Wallet that belongs to the intended recipient of the exported viewing key; used to automatically send the key to the recipient in a secure and private manner
 * @param shareWalletIdAs The wallet id assigned by the sender and used to identify the shared wallet on the recipient's Node.
 */
data class ShareWalletViewingPermissionRequest (
    /* The ID of the Wallet to export a viewing key for */
    val walletId: kotlin.String,
    /* The authorization password for the Wallet */
    val authorization: kotlin.String,
    /* An Address of the Wallet that belongs to the intended recipient of the exported viewing key; used to automatically send the key to the recipient in a secure and private manner */
    val recipientPaymentAddress: kotlin.String,
    /* The wallet id assigned by the sender and used to identify the shared wallet on the recipient's Node. */
    val shareWalletIdAs: kotlin.String
) {

}

