/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models

import org.qedit.kotqedit.models.AnalyticWalletMetadata

/**
 * A single retrieved transaction
 * @param metadata 
 * @param content The detailed information of the transaction; structure depends on the type of transaction
 */
data class AnalyticWalletTx (
    val metadata: AnalyticWalletMetadata? = null,
    /* The detailed information of the transaction; structure depends on the type of transaction */
    val content: kotlin.Any? = null
) {

}

