/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models


/**
 * 
 * @param isIncoming Boolean signifying whether the Assets were issued to the Wallet in question
 * @param issuedBySelf Boolean signifying whether the Wallet used to issue the Assets is the Wallet in question
 * @param senderId The public key of the Wallet that was used to issue the Assets
 * @param recipientAddress The Address the Assets were issued to
 * @param assetId The ID of an Asset Type. It must be a string of length 0 to 40 characters. Allowed characters are lower- and uppercase letters, digits, dot (.), and hyphen (-). It must not end with an hyphen. Asset IDs are case-sensitive. 
 * @param amount The amount of Assets issued
 * @param isConfidential Boolean signifying whether the Issuance was done confidentially
 * @param memo The private memo attached to the Issuance
 */
data class AnalyticIssueWalletTx (
    /* Boolean signifying whether the Assets were issued to the Wallet in question */
    val isIncoming: kotlin.Boolean? = null,
    /* Boolean signifying whether the Wallet used to issue the Assets is the Wallet in question */
    val issuedBySelf: kotlin.Boolean? = null,
    /* The public key of the Wallet that was used to issue the Assets */
    val senderId: kotlin.String? = null,
    /* The Address the Assets were issued to */
    val recipientAddress: kotlin.String? = null,
    /* The ID of an Asset Type. It must be a string of length 0 to 40 characters. Allowed characters are lower- and uppercase letters, digits, dot (.), and hyphen (-). It must not end with an hyphen. Asset IDs are case-sensitive.  */
    val assetId: kotlin.String? = null,
    /* The amount of Assets issued */
    val amount: kotlin.Int? = null,
    /* Boolean signifying whether the Issuance was done confidentially */
    val isConfidential: kotlin.Boolean? = null,
    /* The private memo attached to the Issuance */
    val memo: kotlin.String? = null
) {

}

