/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models


/**
 * 
 * @param walletId The Node-specific identifier of the Wallet that owns the new Group
 * @param memo Memo to be used by the application to define the purpose of the group. Defaults to an empty string.
 */
data class CreateGroupRequest (
    /* The Node-specific identifier of the Wallet that owns the new Group */
    val walletId: kotlin.String,
    /* Memo to be used by the application to define the purpose of the group. Defaults to an empty string. */
    val memo: kotlin.String? = null
) {

}

