/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models


/**
 * 
 * @param walletId The Node-specific identifier of the Wallet that is to leave the Group
 * @param startIndex An offset used to paginate through the available groups; indexing is 0-based; defaults to 0
 * @param numberOfResults Maximal number of results to fetch in this call; defaults to 100
 */
data class GetGroupsRequest (
    /* The Node-specific identifier of the Wallet that is to leave the Group */
    val walletId: kotlin.String,
    /* An offset used to paginate through the available groups; indexing is 0-based; defaults to 0 */
    val startIndex: kotlin.Int? = null,
    /* Maximal number of results to fetch in this call; defaults to 100 */
    val numberOfResults: kotlin.Int? = null
) {

}

