/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models


/**
 * 
 * @param passing Boolean signifying whether the component is healthy
 * @param error Error string describing the component's problem; empty if the component is healthy
 */
data class HealthcheckResponseItem (
    /* Boolean signifying whether the component is healthy */
    val passing: kotlin.Boolean? = null,
    /* Error string describing the component's problem; empty if the component is healthy */
    val error: kotlin.String? = null
) {

}

