/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models


/**
 * 
 * @param walletId The ID under which to import the Wallet; can be different from the ID the Wallet was stored under in the exporting Node
 * @param publicKey The public key of the imported Wallet
 * @param accessKey the encrypted viewing key of the imported Wallet
 */
data class ImportAuditorAccessWalletRequest (
    /* The ID under which to import the Wallet; can be different from the ID the Wallet was stored under in the exporting Node */
    val walletId: kotlin.String,
    /* The public key of the imported Wallet */
    val publicKey: kotlin.String,
    /* the encrypted viewing key of the imported Wallet */
    val accessKey: kotlin.String
) {

}

