/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models

import org.qedit.kotqedit.models.NotificationType

/**
 * A notification including some metadata and a content field whose type depends on the type of notification.
 * @param id The unique identifier of the notification. Can be used for pagination purposes.
 * @param createdAt Timestamp the notification was created at, in RFC-3339 format.
 * @param walletId The ID of the wallet the notification relates to. May be null in cases there is no such specific wallet.
 * @param taskId The ID of the task the notification relates to. May be empty in cases there is no such specific task.
 * @param notificationType 
 * @param content 
 */
data class Notification (
    /* The unique identifier of the notification. Can be used for pagination purposes. */
    val id: kotlin.Int,
    /* Timestamp the notification was created at, in RFC-3339 format. */
    val createdAt: java.time.LocalDateTime,
    /* The ID of the task the notification relates to. May be empty in cases there is no such specific task. */
    val taskId: kotlin.String,
    val notificationType: NotificationType,
    /* The ID of the wallet the notification relates to. May be null in cases there is no such specific wallet. */
    val walletId: kotlin.String? = null,
    val content: kotlin.Any? = null
) {

}

