/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models


import com.squareup.moshi.Json

/**
* Order of results to fetch (either ascending or descending); ordering is chronological where the time is set to when the retrieved object was created
* Values: asc,desc
*/
enum class OrderEnum(val value: kotlin.String){

    @Json(name = "asc") asc("asc"),

    @Json(name = "desc") desc("desc");

}

