/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models


/**
 * An object that includes additional request details
 * @param senderPublicKey The public key of the sender of the confirmation request
 * @param requireConfirmationFrom The public key for the confirmation request receiver
 * @param recipientAddress The address the request was sent to
 * @param assetId 
 * @param amount 
 * @param walletId 
 */
data class TaskData (
    /* The public key of the sender of the confirmation request */
    val senderPublicKey: kotlin.String? = null,
    /* The public key for the confirmation request receiver */
    val requireConfirmationFrom: kotlin.String? = null,
    /* The address the request was sent to */
    val recipientAddress: kotlin.String? = null,
    val assetId: kotlin.String? = null,
    val amount: kotlin.Int? = null,
    val walletId: kotlin.String? = null
) {

}

