/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models


import com.squareup.moshi.Json

/**
* Task type
* Values: transferAsset,issueAsset,createRule,deleteRule,importWallet,deleteWallet,outgoingConfirmRequest,incomingConfirmRequest,cancellation
*/
enum class TaskType(val value: kotlin.String){

    @Json(name = "transfer_asset") transferAsset("transfer_asset"),

    @Json(name = "issue_asset") issueAsset("issue_asset"),

    @Json(name = "create_rule") createRule("create_rule"),

    @Json(name = "delete_rule") deleteRule("delete_rule"),

    @Json(name = "import_wallet") importWallet("import_wallet"),

    @Json(name = "delete_wallet") deleteWallet("delete_wallet"),

    @Json(name = "outgoing_confirm_request") outgoingConfirmRequest("outgoing_confirm_request"),

    @Json(name = "incoming_confirm_request") incomingConfirmRequest("incoming_confirm_request"),

    @Json(name = "cancellation") cancellation("cancellation");

}

