/**
* QEDIT - Asset Transfers
* This SDK provides a programmatic way for interacting with QEDIT's _Asset Transfer_ API. The specification definition file is publicly available [in this repository](https://github.com/QED-it/asset_transfers_dev_guide/). 
*
* OpenAPI spec version: 1.8.0
* Contact: dev@qed-it.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.qedit.kotqedit.models


import com.squareup.moshi.Json

/**
* A fine-grained status of the node's inner state. This field is subject to changes and should not be relied upon during development.
* Values: pendingState,inProgressState,txGeneratedState,confReqSentState,confReqReceivedState,confReqCanceledBySenderState,confReqCanceledByReceiverState,txSubmittedState,failureState,successState
*/
enum class TaskState(val value: kotlin.String){

    @Json(name = "pending_state") pendingState("pending_state"),

    @Json(name = "in_progress_state") inProgressState("in_progress_state"),

    @Json(name = "tx_generated_state") txGeneratedState("tx_generated_state"),

    @Json(name = "conf_req_sent_state") confReqSentState("conf_req_sent_state"),

    @Json(name = "conf_req_received_state") confReqReceivedState("conf_req_received_state"),

    @Json(name = "conf_req_canceled_by_sender_state") confReqCanceledBySenderState("conf_req_canceled_by_sender_state"),

    @Json(name = "conf_req_canceled_by_receiver_state") confReqCanceledByReceiverState("conf_req_canceled_by_receiver_state"),

    @Json(name = "tx_submitted_state") txSubmittedState("tx_submitted_state"),

    @Json(name = "failure_state") failureState("failure_state"),

    @Json(name = "success_state") successState("success_state");

}

